# Project Context - Forge
# RoyalBit Asimov Project Configuration

identity:
  name: "forge"
  type: rust
  tagline: "AI hallucinates numbers. Forge doesn't."
  description: "YAML-based financial modeling with Excel formula evaluation"
  # Version sources: Cargo.toml (current), roadmap.yaml (future), CHANGELOG.md (past)

# ═══════════════════════════════════════════════════════════════════════════════
# RELATED PROJECTS
# ═══════════════════════════════════════════════════════════════════════════════

external_projects:
  forge-demo:
    path: "../forge-demo"
    description: "E2E validation tool for forge-demo binary"
    github: "https://github.com/royalbit/forge-demo"
    type: "git"
    binary: "forge-e2e"  # The E2E test runner, NOT forge-demo itself
    distribution: "github"  # Cross-platform builds → GitHub Releases (royalbit/forge-demo)
    contents:
      - "README.md - Public documentation"
      - "docs/FUNCTIONS.md - Demo function reference (47 functions)"
      - "tests/e2e/ - E2E test YAML files"
      - "run-demo.sh - Downloads forge-demo + forge-e2e, runs tests"

  royalbit-website:
    path: "~/src/sites/royalbit.ca"
    description: "RoyalBit company website"
    type: "git (gitolite)"
    forge_page: "html/forge/index.html"
    contents:
      - "html/forge/ - Forge product page"
      - "html/forge/index.html - Download links to GitHub releases"
    release:
      - "git repo, need to update the .env version"
      - "docker, use the ./build and the ./stop and ./start to redeploy"

# ═══════════════════════════════════════════════════════════════════════════════
# BUILD CONFIGURATION - USE MAKEFILE
# ═══════════════════════════════════════════════════════════════════════════════
# IMPORTANT: Always use `make` targets instead of raw cargo commands.
# The Makefile handles cross-compilation, UPX compression, and GitHub releases.

makefile:
  # ─────────────────────────────────────────────────────────────────────────────
  # INSTALL TO ~/bin (use these for local development)
  # ─────────────────────────────────────────────────────────────────────────────
  install_forge: "make install-forge"        # Build enterprise + install to ~/bin
  install_demo: "make install-forge-demo"    # Build demo + install to ~/bin
  install_all: "make install-all"            # Both binaries to ~/bin

  # ─────────────────────────────────────────────────────────────────────────────
  # CROSS-PLATFORM BUILDS (5 platforms → dist/)
  # ─────────────────────────────────────────────────────────────────────────────
  cross_demo: "make cross-forge-demo"        # All 5 platforms for forge-demo
  cross_enterprise: "make cross-forge"       # All 5 platforms for forge

  # ─────────────────────────────────────────────────────────────────────────────
  # GITHUB RELEASE (auto-detects version from Cargo.toml)
  # ─────────────────────────────────────────────────────────────────────────────
  publish: "make publish-demo"               # Build + publish to royalbit/forge-demo

  # ─────────────────────────────────────────────────────────────────────────────
  # QUALITY CHECKS
  # ─────────────────────────────────────────────────────────────────────────────
  test: "make test"                          # Run all tests
  lint: "make lint"                          # Clippy with pedantic lints
  format: "make format"                      # Format code
  check: "make check"                        # Quick dev check (format + lint + unit tests)
  pre_commit: "make pre-commit"              # Full pre-commit check

quality:
  test: "make test"
  lint: "make lint"
  format: "make format"
  build_demo: "make install-forge-demo"
  build_enterprise: "make install-forge"

binaries:
  # ─────────────────────────────────────────────────────────────────────────────
  # PUBLIC - GitHub Releases (royalbit/forge)
  # ─────────────────────────────────────────────────────────────────────────────
  demo:
    name: "forge-demo"
    features: []
    functions: 47
    distribution: "github"  # Cross-platform builds → GitHub Releases
    github_repo: "royalbit/forge-demo"
    platforms: ["macos-arm64", "macos-x86_64", "linux-x86_64", "linux-arm64", "windows"]

  # ─────────────────────────────────────────────────────────────────────────────
  # PROPRIETARY - Local only (~/bin), NEVER push to GitHub
  # ─────────────────────────────────────────────────────────────────────────────
  enterprise:
    name: "forge"
    features: ["full"]
    functions: 159
    distribution: "local"  # Build for current machine only → ~/bin
    install_path: "~/bin"
    note: "Proprietary. Self-hosted. NEVER push to GitHub."
  server:
    name: "forge-server"
    features: ["full"]
    description: "REST API server"
    distribution: "local"
    install_path: "~/bin"
  mcp:
    name: "forge-mcp"
    features: ["full"]
    description: "AI/MCP server for Claude, GPT"
    distribution: "local"
    install_path: "~/bin"

# ═══════════════════════════════════════════════════════════════════════════════
# KEY FILES
# ═══════════════════════════════════════════════════════════════════════════════

files:
  source:
    - "src/main.rs - CLI entry point"
    - "src/lib.rs - Library root"
    - "src/functions/registry.rs - Function registry (single source of truth)"
    - "src/core/array_calculator/ - Formula evaluation engine"
    - "src/cli/commands/ - CLI command implementations"
  config:
    - "Cargo.toml - Dependencies and metadata"
    - ".asimov/roadmap.yaml - Version roadmap"
    - ".asimov/project.yaml - This file"
  docs:
    - "README.md - Internal documentation"
    - "docs/architecture/ - ADRs"
  tests:
    - "tests/ - Integration and E2E tests"
    - "tests/e2e_libreoffice_tests.rs - External validation against Gnumeric/LibreOffice"

# ═══════════════════════════════════════════════════════════════════════════════
# CODING PATTERNS
# ═══════════════════════════════════════════════════════════════════════════════

patterns:
  - "Result<T, E> for errors, no panics"
  - "thiserror for custom errors (ForgeError)"
  - "No unwrap() in library code"
  - "Use clippy lints as errors"
  - "#[cfg(feature = \"full\")] for enterprise-only code"
  - "Unit tests in same file (#[cfg(test)] mod tests)"
  - "No file > 1,500 lines"
  - "Zero warnings policy"

# ═══════════════════════════════════════════════════════════════════════════════
# RELEASE CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

release:
  # Use Makefile for all release operations
  local_install: "make install-forge"         # Enterprise to ~/bin
  cross_build: "make cross-forge-demo"        # All 5 platforms
  publish: "make publish-demo"                # Build + GitHub release

  profile: |
    [profile.release]
    opt-level = 3
    lto = true
    codegen-units = 1
    strip = true
    panic = "abort"
  cross_compile: "cargo-zigbuild (via Makefile)"

  # ─────────────────────────────────────────────────────────────────────────────
  # DISTRIBUTION RULES (CRITICAL - READ BEFORE RELEASING)
  # ─────────────────────────────────────────────────────────────────────────────
  #
  # ONLY ONE PUBLIC REPO: royalbit/forge-demo
  # (royalbit/forge no longer exists - redirects to forge-demo)
  #
  distribution:
    # PUBLIC: Both binaries → GitHub Releases (royalbit/forge-demo)
    forge-demo:
      target: "github"
      repo: "royalbit/forge-demo"
      source: "this"  # Built from this repo (forge)
      platforms:
        - "aarch64-apple-darwin (macOS ARM64)"
        - "x86_64-apple-darwin (macOS Intel)"
        - "x86_64-unknown-linux-musl (Linux x86_64)"
        - "aarch64-unknown-linux-musl (Linux ARM64)"
        - "x86_64-pc-windows-gnu (Windows)"
      asset_names:
        - "forge-demo-macos-arm64"
        - "forge-demo-macos-x86_64"
        - "forge-demo-linux-x86_64"
        - "forge-demo-linux-arm64"
        - "forge-demo-windows.exe"

    forge-e2e:
      target: "github"
      repo: "royalbit/forge-demo"
      source: "../forge-demo"  # Built from forge-demo repo

    # PROPRIETARY: Local only → ~/bin (NEVER GitHub)
    forge:
      target: "local"
      install_path: "~/bin"
      platforms: ["current"]  # Only build for current machine
      note: "PROPRIETARY. NEVER push to GitHub. Self-hosted infrastructure only."
    forge-server:
      target: "local"
      install_path: "~/bin"
    forge-mcp:
      target: "local"
      install_path: "~/bin"
