# Project Context - Forge
# RoyalBit Asimov Project Configuration

identity:
  name: "forge"
  type: rust
  tagline: "AI hallucinates numbers. Forge doesn't."
  description: "YAML-based financial modeling with Excel formula evaluation"
  # Version sources: Cargo.toml (current), roadmap.yaml (future), CHANGELOG.md (past)

# ═══════════════════════════════════════════════════════════════════════════════
# RELATED PROJECTS
# ═══════════════════════════════════════════════════════════════════════════════

external_projects:
  forge-demo:
    path: "../forge-demo"
    description: "Public demo repository (36 functions)"
    github: "https://github.com/royalbit/forge-demo"
    type: "git"
    contents:
      - "README.md - Public documentation"
      - "docs/FUNCTIONS.md - Demo function reference"
      - "tests/ - E2E test files and runner"
      - "tests/forge-demo - Demo binary for testing"

  royalbit-website:
    path: "~/src/sites/royalbit.ca"
    description: "RoyalBit company website"
    type: "git (gitolite)"
    forge_page: "html/forge/index.html"
    contents:
      - "html/forge/ - Forge product page"
      - "html/forge/index.html - Download links to GitHub releases"

# ═══════════════════════════════════════════════════════════════════════════════
# BUILD CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

quality:
  test: "cargo test --features full"
  lint: "cargo clippy --features full -- -D warnings"
  format: "cargo fmt --check"
  build_demo: "cargo build --release --bin forge-demo"
  build_enterprise: "cargo build --release --features full"

binaries:
  demo:
    name: "forge-demo"
    features: []
    functions: 36
    public: true
  enterprise:
    name: "forge"
    features: ["full"]
    functions: 159
    public: false
  server:
    name: "forge-server"
    features: ["full"]
    description: "REST API server"
  mcp:
    name: "forge-mcp"
    features: ["full"]
    description: "AI/MCP server for Claude, GPT"

# ═══════════════════════════════════════════════════════════════════════════════
# KEY FILES
# ═══════════════════════════════════════════════════════════════════════════════

files:
  source:
    - "src/main.rs - CLI entry point"
    - "src/lib.rs - Library root"
    - "src/functions/registry.rs - Function registry (single source of truth)"
    - "src/core/array_calculator/ - Formula evaluation engine"
    - "src/cli/commands/ - CLI command implementations"
  config:
    - "Cargo.toml - Dependencies and metadata"
    - ".asimov/roadmap.yaml - Version roadmap"
    - ".asimov/project.yaml - This file"
  docs:
    - "README.md - Internal documentation"
    - "docs/architecture/ - ADRs"
  tests:
    - "tests/ - Integration and E2E tests"
    - "tests/e2e_libreoffice_tests.rs - External validation against Gnumeric/LibreOffice"

# ═══════════════════════════════════════════════════════════════════════════════
# CODING PATTERNS
# ═══════════════════════════════════════════════════════════════════════════════

patterns:
  - "Result<T, E> for errors, no panics"
  - "thiserror for custom errors (ForgeError)"
  - "No unwrap() in library code"
  - "Use clippy lints as errors"
  - "#[cfg(feature = \"full\")] for enterprise-only code"
  - "Unit tests in same file (#[cfg(test)] mod tests)"
  - "No file > 1,500 lines"
  - "Zero warnings policy"

# ═══════════════════════════════════════════════════════════════════════════════
# RELEASE CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

release:
  profile: |
    [profile.release]
    opt-level = 3
    lto = true
    codegen-units = 1
    strip = true
    panic = "abort"
  platforms:
    - "aarch64-apple-darwin (macOS ARM64)"
    - "x86_64-apple-darwin (macOS Intel)"
    - "x86_64-unknown-linux-musl (Linux x86_64)"
    - "aarch64-unknown-linux-musl (Linux ARM64)"
    - "x86_64-pc-windows-gnu (Windows)"
  cross_compile: "cargo-zigbuild"
  distribution:
    demo: "GitHub Releases (royalbit/forge-demo)"
    enterprise: "Licensed customers only"
