identity:
  name: "forge"
  type: rust

description: >
  YAML-based financial modeling engine with Excel formula evaluation.
  Git-native. Deterministic. Validated against Gnumeric and R.

stack:
  - rust
  - clap (CLI)
  - actix-web (API server)
  - tower/jsonrpc (MCP server)
  - statrs (statistics)

conventions:
  - "Result<T, E> for errors, no panics, no unwrap() in library code"
  - "Unit tests in same file (#[cfg(test)] mod tests)"
  - "Zero warnings policy, clippy pedantic"
  - "No file > 1,500 lines"
  - "MIT OR Apache-2.0 license"
  - "make targets over raw cargo commands"
